version: '3.8'
services:

  nginx:
    image: nginx:latest
    build: ./nginx
    container_name: vtb_nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default

  vtb-backend:
    image: vtb-backend:latest
    ports:
      - "${BACKEND_PORT_EXTERNAL}:${BACKEND_PORT_INTERNAL}"
    environment:
      NODE_ENV: ${BACKEND_NODE_ENV}
      HOST: ${BACKEND_HOST}
      ADDRESS: ${ADDRESS}
      SWAGGER_PATH: ${SWAGGER_PATH}
      PORT: ${BACKEND_PORT_INTERNAL}

      DB_USER: ${DB_USER}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_NAME: ${DB_NAME}

      JWT_ACCESS: ${JWT_ACCESS}
      JWT_REFRESH: ${JWT_REFRESH}
      JWT_RECOVERY: ${JWT_RECOVERY}

      JWT_ACCESS_EXP: ${JWT_ACCESS_EXP}
      JWT_REFRESH_EXP: ${JWT_REFRESH_EXP}
      JWT_RECOVERY_EXP: ${JWT_RECOVERY_EXP}

      ADMIN_KEY: ${ADMIN_KEY}

      UCALLER_INIT_CALL_URL: ${UCALLER_INIT_CALL_URL}
      UCALLER_SECRET_KEY: ${UCALLER_SECRET_KEY}
      UCALLER_SERVICE_ID: ${UCALLER_SERVICE_ID}

      AES_CIPHER_KEY: ${AES_CIPHER_KEY}
      AES_CIPHER_IV: ${AES_CIPHER_IV}

      ETHERSCAN_API_KEY: ${ETHERSCAN_API_KEY}
      ETHERSCAN_BASE_URL: ${ETHERSCAN_BASE_URL}

      OPEN_EXCHANGE_RATES_KEY: ${OPEN_EXCHANGE_RATES_KEY}
    networks:
      - default

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}      
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME}   
    ports:
      - "${DB_PORT_INTERNAL}:${DB_PORT_EXTERNAL}"                  
    volumes:
      - "${POSTGRES_VOLUME}"
    networks:
      - default

volumes:
  postgres_data:                 

networks:
  postgres_network:    
